# Generated by Django 4.2.13 on 2026-04-05 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="postlike",
            name="reaction_type",
            field=models.CharField(
                choices=[
                    ("like", "Like"),
                    ("love", "Love"),
                    ("haha", "Haha"),
                    ("wow", "Wow"),
                    ("sad", "Sad"),
                    ("angry", "Angry"),
                ],
                default="like",
                max_length=10,
            ),
        ),
    ]
